version: '3'
services:
  sdt-app:
    image: sdt_img
    container_name: sdt_ctr
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./sdt_questions", "./src/file_1.txt"]
    ports:
      - "8080:8080"
