name: Docker Build

on:
  push:
    branches:
      - USDT-34-Github-action-dockerfile
      - dev

jobs:
  build-img:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t sdt_questions_img .

  build-compose:
    name: Build Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Compose
        run: docker-compose up --build
